// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw-sYluHheG4NFGBkhmjyh_vHX3o6Z7fA',
    appId: '1:32441279740:web:ab48ad6ba68b8e89e72379',
    messagingSenderId: '32441279740',
    projectId: 'cinehub-mv',
    authDomain: 'cinehub-mv.firebaseapp.com',
    storageBucket: 'cinehub-mv.appspot.com',
    measurementId: 'G-6E3GFT3H0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdUsfFsHh0_vErI-KGYBu4L2OCgn7ZMIs',
    appId: '1:32441279740:android:57d95833dc6ccea1e72379',
    messagingSenderId: '32441279740',
    projectId: 'cinehub-mv',
    storageBucket: 'cinehub-mv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_kJKhN7KM88B-HZTLgKrI9BcoKfrlG_Q',
    appId: '1:32441279740:ios:3da7f42e142f8f55e72379',
    messagingSenderId: '32441279740',
    projectId: 'cinehub-mv',
    storageBucket: 'cinehub-mv.appspot.com',
    iosBundleId: 'com.example.travl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_kJKhN7KM88B-HZTLgKrI9BcoKfrlG_Q',
    appId: '1:32441279740:ios:836b35738ed4531ae72379',
    messagingSenderId: '32441279740',
    projectId: 'cinehub-mv',
    storageBucket: 'cinehub-mv.appspot.com',
    iosBundleId: 'com.example.travl.RunnerTests',
  );
}
